export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const logout = <i className="fa-solid fa-sign-out"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const users = <i className="fa-solid fa-users-between-lines"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const del = <i className="fa-solid fa-trash"></i>
export const plus = <i className="fa-solid fa-plus"></i>