# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy full stack app to Azure Web App - finance-tracker-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
        working-directory: ./frontend

      - name: Package frontend
        run: zip -r frontend.zip build
        working-directory: ./frontend

      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./backend

      - name: Package backend
        run: zip -r backend.zip .
        working-directory: ./backend

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/frontend.zip
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Download backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Unzip frontend artifact
        run: unzip frontend.zip -d ./frontend

      - name: Unzip backend artifact
        run: unzip backend.zip -d ./backend
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy backend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'finance-tracker-app'
          slot-name: 'Production'
          package: ./backend

      - name: Deploy frontend to Azure Storage
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'finance-tracker-frontend'
          slot-name: 'Production'
          package: ./frontend

          
